In [1]:
import os

# Créer le dossier principal du projet
os.makedirs("Energy_Project/data", exist_ok=True)
os.makedirs("Energy_Project/notebooks", exist_ok=True)
os.makedirs("Energy_Project/dashboard", exist_ok=True)
os.makedirs("Energy_Project/outputs", exist_ok=True)

# Créer le fichier README
with open("Energy_Project/README.md", "w") as f:
    f.write("# Projet d’optimisation énergétique hybride solaire-diesel-batterie\n")

print("Structure du projet créée avec succès !")

Structure du projet créée avec succès !

In [2]:
import os

print(os.listdir("Energy_Project/data"))

[]

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
solar = pd.read_csv(
    "../Data/abuja_solar_2025.csv.csv",
    skiprows=9
)

In [5]:
solar.head()

   YEAR  MO  DY  ALLSKY_SFC_SW_DWN
0  2025   1   1             5.9369
1  2025   1   2             5.9450
2  2025   1   3             5.5214
3  2025   1   4             5.6784
4  2025   1   5             5.9743

In [6]:
system_size = 5  # kW

In [7]:
solar["Solar_Output"] = (
    solar["ALLSKY_SFC_SW_DWN"] * system_size
)

In [8]:
solar.head()

   YEAR  MO  DY  ALLSKY_SFC_SW_DWN  Solar_Output
0  2025   1   1             5.9369       29.6845
1  2025   1   2             5.9450       29.7250
2  2025   1   3             5.5214       27.6070
3  2025   1   4             5.6784       28.3920
4  2025   1   5             5.9743       29.8715

In [9]:
solar["Load_kWh"] = 40 #KW/day

In [10]:
# Déficit énergétique (demande - production solaire)
solar["Energy_Gap"] = (
    solar["Load_kWh"] - solar["Solar_Output"]
)

solar[
    ["Solar_Output",
     "Load_kWh",
     "Energy_Gap"]
].head()

   Solar_Output  Load_kWh  Energy_Gap
0       29.6845        40     10.3155
1       29.7250        40     10.2750
2       27.6070        40     12.3930
3       28.3920        40     11.6080
4       29.8715        40     10.1285